"""
Hypothesis 1 – Code Generation (Runtime)
=========================================
RQ1: Is there a statistically significant difference in the execution time
     of SQL queries generated by ChatGPT Mini and Gemini Flash?

Paired comparison on problems accepted by BOTH models.

Steps
-----
1. Extract paired runtime data (problems accepted by both models)
2. Compute differences  d_i = ChatGPT_runtime_i − Gemini_runtime_i
3. Shapiro-Wilk normality test on the differences
4. QQ plot of the differences
5. If normal → Paired t-test  |  If not normal → Wilcoxon signed-rank test
6. Print results and save QQ plot

Requirements: pip install matplotlib scipy numpy
"""

import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import os

OUTPUT_DIR = os.path.join("..", "Report", "charts")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Data (same as graphs.py) ────────────────────────────────────────────────

chatgpt = {
    "hard": [
        (185,102,True),(262,126,True),(601,68,True),(3451,82,False),
        (3374,88,True),(3482,76,True),(3617,None,False),(3764,70,True),
        (3832,69,True),(3673,84,True),(1581,136,True),(2356,83,True),
        (1978,73,True),(1965,113,True),(1890,229,True),(1873,66,True),
        (1789,164,True),(1757,73,True),(1741,81,True),
    ],
    "medium": [
        (176,82,True),(177,86,True),(178,79,True),(180,75,True),
        (184,116,True),(550,69,True),(570,67,True),(585,82,True),
        (602,70,True),(608,102,True),(626,77,True),(1045,93,True),
        (1070,102,True),(1158,764,True),(1164,85,True),(1174,82,True),
        (1193,70,True),(1204,213,True),(1321,78,True),(1341,159,True),
        (1393,72,True),
    ],
    "easy": [
        (175,100,True),(181,67,True),(182,67,True),(183,103,True),
        (196,71,True),(197,79,True),(511,79,True),(577,118,True),
        (584,88,True),(586,88,True),(595,91,True),(596,70,True),
        (607,151,True),(610,96,True),(619,105,True),(620,79,True),
        (627,92,True),(1050,68,True),(1068,98,True),(1075,135,True),
        (1084,84,True),
    ],
}

gemini = {
    "hard": [
        (185,128,True),(262,94,True),(601,82,True),(3451,84,True),
        (3374,84,False),(3482,94,True),(3673,88,True),(3617,120,True),
        (3832,None,False),(3764,106,True),(1581,80,True),(2356,78,True),
        (1978,68,True),(1965,71,True),(1890,88,True),(1873,82,True),
        (1789,102,True),(1757,81,True),(1741,96,True),
    ],
    "medium": [
        (176,90,True),(177,103,True),(178,None,False),(180,74,True),
        (184,130,True),(550,80,True),(570,102,True),(585,71,True),
        (602,75,True),(608,83,True),(626,79,True),(1045,118,True),
        (1070,83,True),(1158,147,True),(1164,62,True),(1174,73,True),
        (1193,222,True),(1204,65,True),(1321,70,True),(1341,147,True),
        (1393,76,True),
    ],
    "easy": [
        (175,114,True),(181,80,True),(182,70,True),(183,94,True),
        (196,70,True),(197,68,True),(511,74,True),(577,644,True),
        (584,79,True),(586,79,True),(595,78,True),(596,67,True),
        (607,121,True),(610,80,True),(619,118,True),(620,75,True),
        (627,90,True),(1050,93,True),(1068,112,True),(1075,136,True),
        (1084,445,True),
    ],
}

# ── 1. Build paired data ────────────────────────────────────────────────────

diffs_list = ["easy", "medium", "hard"]

# Build lookup: pid -> runtime  for accepted problems with valid runtime
gpt_map = {}
gem_map = {}
for diff in diffs_list:
    for pid, rt, ok in chatgpt[diff]:
        if ok and rt is not None:
            gpt_map[pid] = rt
    for pid, rt, ok in gemini[diff]:
        if ok and rt is not None:
            gem_map[pid] = rt

# Paired problems: accepted by BOTH with valid runtimes
shared_pids = sorted(set(gpt_map.keys()) & set(gem_map.keys()))

gpt_runtimes = np.array([gpt_map[pid] for pid in shared_pids], dtype=float)
gem_runtimes = np.array([gem_map[pid] for pid in shared_pids], dtype=float)
differences  = gpt_runtimes - gem_runtimes   # d_i = ChatGPT - Gemini

print("=" * 65)
print("HYPOTHESIS 1 - RUNTIME STATISTICAL ANALYSIS")
print("=" * 65)
print(f"\nPaired problems (accepted by both): {len(shared_pids)}")
print(f"Problem IDs: {shared_pids}")
print(f"\nChatGPT runtimes: mean={np.mean(gpt_runtimes):.2f}, median={np.median(gpt_runtimes):.2f}, std={np.std(gpt_runtimes, ddof=1):.2f}")
print(f"Gemini  runtimes: mean={np.mean(gem_runtimes):.2f}, median={np.median(gem_runtimes):.2f}, std={np.std(gem_runtimes, ddof=1):.2f}")
print(f"\nDifferences (ChatGPT - Gemini):")
print(f"  mean={np.mean(differences):.2f}, median={np.median(differences):.2f}, std={np.std(differences, ddof=1):.2f}")

# ── 2. Shapiro-Wilk Normality Test on the differences ───────────────────────

shapiro_stat, shapiro_p = stats.shapiro(differences)
alpha = 0.05

print(f"\n{'=' * 65}")
print("NORMALITY TEST -- Shapiro-Wilk (on paired differences)")
print(f"{'=' * 65}")
print(f"  W-statistic = {shapiro_stat:.4f}")
print(f"  p-value     = {shapiro_p:.6f}")
print(f"  alpha       = {alpha}")

if shapiro_p > alpha:
    is_normal = True
    print(f"  => p = {shapiro_p:.6f} > {alpha}  =>  FAIL TO REJECT H0 of normality")
    print(f"  => The differences CAN be assumed normally distributed.")
else:
    is_normal = False
    print(f"  => p = {shapiro_p:.6f} <= {alpha}  =>  REJECT H0 of normality")
    print(f"  => The differences are NOT normally distributed.")

# -- 3. QQ Plot of the differences -----------------------------------------------

fig, ax = plt.subplots(figsize=(6, 6))
res = stats.probplot(differences, dist="norm", plot=ax)
ax.set_title("Q-Q Plot of Paired Runtime Differences\n(ChatGPT - Gemini)", fontsize=13, fontweight="bold", pad=12)
ax.set_xlabel("Theoretical Quantiles", fontsize=11)
ax.set_ylabel("Sample Quantiles (ms)", fontsize=11)

# Add Shapiro-Wilk result as annotation
ax.annotate(
    f"Shapiro-Wilk: W={shapiro_stat:.4f}, p={shapiro_p:.4f}",
    xy=(0.05, 0.95), xycoords="axes fraction",
    fontsize=9, verticalalignment="top",
    bbox=dict(boxstyle="round,pad=0.4", facecolor="lightyellow", edgecolor="gray", alpha=0.9),
)

fig.tight_layout()
qq_path = os.path.join(OUTPUT_DIR, "6_qq_plot_runtime_differences.png")
fig.savefig(qq_path, bbox_inches="tight", dpi=150)
plt.close(fig)
print(f"\n  QQ plot saved: {qq_path}")

# -- 4. Statistical Test ---------------------------------------------------------

print(f"\n{'=' * 65}")
if is_normal:
    print("PAIRED t-TEST (data is normally distributed)")
    print(f"{'=' * 65}")
    t_stat, t_p = stats.ttest_rel(gpt_runtimes, gem_runtimes)
    print(f"  t-statistic = {t_stat:.4f}")
    print(f"  p-value     = {t_p:.6f}")
    print(f"  alpha       = {alpha}")
    test_name = "Paired t-test"
    test_stat_val = t_stat
    test_p_val = t_p
    test_stat_name = "t"
else:
    print("WILCOXON SIGNED-RANK TEST (data is NOT normally distributed)")
    print(f"{'=' * 65}")
    w_stat, w_p = stats.wilcoxon(differences)
    print(f"  W-statistic = {w_stat:.4f}")
    print(f"  p-value     = {w_p:.6f}")
    print(f"  alpha       = {alpha}")
    test_name = "Wilcoxon signed-rank test"
    test_stat_val = w_stat
    test_p_val = w_p
    test_stat_name = "W"

# -- 5. Decision -----------------------------------------------------------------

print(f"\n{'=' * 65}")
print("DECISION")
print(f"{'=' * 65}")
if test_p_val <= alpha:
    print(f"  p = {test_p_val:.6f} <= {alpha}  =>  REJECT H0")
    print(f"  => There IS a statistically significant difference in execution times.")
    decision = "reject"
else:
    print(f"  p = {test_p_val:.6f} > {alpha}  =>  FAIL TO REJECT H0")
    print(f"  => There is NO statistically significant difference in execution times.")
    decision = "fail_to_reject"

# -- 6. Effect size (Cohen's d for paired samples) -------------------------------

cohens_d = np.mean(differences) / np.std(differences, ddof=1)
print(f"\n  Cohen's d (effect size) = {cohens_d:.4f}")
if abs(cohens_d) < 0.2:
    effect_label = "negligible"
elif abs(cohens_d) < 0.5:
    effect_label = "small"
elif abs(cohens_d) < 0.8:
    effect_label = "medium"
else:
    effect_label = "large"
print(f"  Interpretation: {effect_label} effect")

print(f"\n{'=' * 65}")
print("SUMMARY")
print(f"{'=' * 65}")
print(f"  Paired observations : {len(shared_pids)}")
print(f"  Normality test      : Shapiro-Wilk (W={shapiro_stat:.4f}, p={shapiro_p:.4f})")
print(f"  Normal?             : {'Yes' if is_normal else 'No'}")
print(f"  Statistical test    : {test_name}")
print(f"  Test statistic      : {test_stat_name}={test_stat_val:.4f}")
print(f"  p-value             : {test_p_val:.6f}")
print(f"  alpha               : {alpha}")
print(f"  Decision            : {'Reject H0' if decision == 'reject' else 'Fail to reject H0'}")
print(f"  Effect size         : Cohen's d = {cohens_d:.4f} ({effect_label})")
print(f"  QQ plot             : {qq_path}")
print(f"{'=' * 65}")
